use std::{env, fs, path::Path, path::PathBuf};

const HEADER: &str = "../../vendor/nv-codec-headers/include/ffnvcodec/nvEncodeAPI.h";

fn main() {
    println!("cargo:rerun-if-changed={HEADER}");
    println!("cargo:rerun-if-changed=build.rs");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));

    generate_bindings(&out);
    generate_guids(&out);
    generate_struct_versions(&out);
}

/// Parse nvEncodeAPI.h as if for a non-Windows target.
///
/// The header only pulls in `windows.h` under `_WIN32`; otherwise it uses its own
/// GUID and NVENC_RECT definitions, which are built from fixed-width types and are
/// bit-identical to the Windows ones. That keeps bindgen independent of the Windows
/// SDK and stops it from dragging in all of windows.h.
///
/// The calling convention differs on paper (`__stdcall` vs default), but x86_64
/// Windows has only one, so the generated `extern "C"` signatures are correct.
fn generate_bindings(out: &Path) {
    bindgen::Builder::default()
        .header(HEADER)
        .allowlist_type("^NV_ENC.*")
        .allowlist_type("^NVENC.*")
        .allowlist_type("^GUID$")
        .allowlist_function("^NvEncodeAPI.*")
        .allowlist_var("^NV_ENC.*")
        .allowlist_var("^NVENC.*")
        // The header defines its GUIDs as `static const GUID`. bindgen turns those
        // into extern statics, which have no symbol anywhere to link against -- that
        // only surfaces as an unresolved-external at link time. generate_guids()
        // emits them as real constants instead.
        .blocklist_item("^NV_ENC.*_GUID$")
        .derive_default(true)
        .derive_debug(true)
        .prepend_enum_name(false)
        .layout_tests(false)
        .generate()
        .expect("bindgen failed on nvEncodeAPI.h")
        .write_to_file(out.join("nvenc_sys.rs"))
        .expect("could not write nvenc_sys.rs");
}

/// Emit the codec/preset/profile/tuning GUIDs as Rust constants.
///
/// They are `static const GUID` in the header, which bindgen cannot turn into
/// usable constants, so they are extracted textually instead. Copying them by hand
/// would risk silent transcription errors that only show up as a cryptic
/// NV_ENC_ERR_INVALID_PARAM at runtime.
fn generate_guids(out: &Path) {
    let src = fs::read_to_string(HEADER).expect("could not read nvEncodeAPI.h");

    let re = regex::Regex::new(
        r"(?s)static\s+const\s+GUID\s+(\w+)\s*=\s*\{\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*\{([^}]*)\}",
    )
    .expect("bad GUID regex");

    let mut rs = String::from("// @generated by build.rs from nvEncodeAPI.h -- do not edit.\n\n");
    let mut count = 0usize;

    for cap in re.captures_iter(&src) {
        let (name, d1, d2, d3) = (&cap[1], &cap[2], &cap[3], &cap[4]);
        let bytes: Vec<&str> = cap[5]
            .split(',')
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .collect();

        assert_eq!(
            bytes.len(),
            8,
            "GUID {name}: expected 8 bytes in Data4, found {}",
            bytes.len()
        );

        rs.push_str(&format!(
            "pub const {name}: GUID = GUID {{ Data1: {d1}, Data2: {d2}, Data3: {d3}, Data4: [{}] }};\n",
            bytes.join(", ")
        ));
        count += 1;
    }

    // Guard against the header format changing under us and silently yielding nothing.
    assert!(
        count >= 20,
        "only {count} GUIDs extracted from nvEncodeAPI.h -- header format changed?"
    );

    fs::write(out.join("nvenc_guids.rs"), rs).expect("could not write nvenc_guids.rs");
    println!("cargo:warning=lanrec: extracted {count} NVENC GUIDs");
}

/// Emit the `*_VER` struct version constants.
///
/// Every NVENC struct carries a `version` field that the driver validates before
/// looking at anything else; get it wrong and every call returns a bare
/// NV_ENC_ERR_INVALID_VERSION with no hint as to which struct was at fault.
///
/// The values come from the function-like macro `NVENCAPI_STRUCT_VERSION`, which
/// bindgen cannot evaluate, so it silently emits nothing for them. They are
/// re-derived here from the header text rather than transcribed, because these
/// numbers change between SDK releases and a stale hand-copied constant would be
/// a very quiet bug.
fn generate_struct_versions(out: &Path) {
    let src = fs::read_to_string(HEADER).expect("could not read nvEncodeAPI.h");

    // Two spellings appear in the header:
    //   #define NV_ENC_RC_PARAMS_VER NVENCAPI_STRUCT_VERSION(1)
    //   #define NV_ENC_CONFIG_VER   (NVENCAPI_STRUCT_VERSION(9) | ( 1u<<31 ))
    let re = regex::Regex::new(
        r"(?m)^#define\s+(NV_ENC\w*_VER)\s+\(?\s*NVENCAPI_STRUCT_VERSION\s*\(\s*(\d+)\s*\)\s*(\|\s*\(\s*1u?\s*<<\s*31\s*\))?",
    )
    .expect("bad struct-version regex");

    let mut rs = String::from(
        "// @generated by build.rs from nvEncodeAPI.h -- do not edit.\n\n\
         /// Mirrors the NVENCAPI_STRUCT_VERSION macro.\n\
         pub const fn nvenc_struct_version(ver: u32) -> u32 {\n\
         \x20   NVENCAPI_VERSION | (ver << 16) | (0x7 << 28)\n\
         }\n\n",
    );
    let mut count = 0usize;

    for cap in re.captures_iter(&src) {
        let name = &cap[1];
        let ver = &cap[2];
        let high_bit = if cap.get(3).is_some() {
            " | (1 << 31)"
        } else {
            ""
        };
        rs.push_str(&format!(
            "pub const {name}: u32 = nvenc_struct_version({ver}){high_bit};\n"
        ));
        count += 1;
    }

    assert!(
        count >= 25,
        "only {count} struct versions extracted from nvEncodeAPI.h -- header format changed?"
    );

    fs::write(out.join("nvenc_versions.rs"), rs).expect("could not write nvenc_versions.rs");
    println!("cargo:warning=lanrec: extracted {count} NVENC struct versions");
}
